version: "3.8"
services:
  database:
    container_name: example-mongodb-container
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=example
      - MONGO_INITDB_USERNAME=kajame
      - MONGO_INITDB_PASSWORD=111111
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./backup-mongo:/backup-mongo
      - ./db:/data/db